### ISSUE TITLE
Item_person.html display error

### ISSUE THREAD

**Issue by jthake** [Hyperfish/SPO-EmployeeDirectory#4]
In my tenant, getting this error

`Display Error: The display template had an error. You can correct it by fixing the template or by changing the display template used in either the Web Part properties or Result Types.
 
~sitecollection/_catalogs/masterpage/_EmployeeDirectory/Display Templates/Search/Item_Person_Table.html: Data at the root level is invalid. Line 1, position 1..`

I'm guessing its this line in the file:
`var accountName = ctx.CurrentItem.AccountName.substr(ctx.CurrentItem.AccountName.lastIndexOf('|') + 1);`

The display template was working fine in the previous version on this tenant listing all three users in the tenant.

**Comment by sympmarc** [comment]
All fixed?

**Comment by jthake** [comment]
Yes. THere were two horrible extra characters at beginning of file. guessing from .the merge of PR.
